version: '3.4'

services:
  centroclinico.ui.mvc:
    image: ${DOCKER_REGISTRY-}centroclinicouimvc
    build:
      context: .
      dockerfile: UI/CentroClinico.UI.MVC/Dockerfile
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: X369408
    ports:
      - 3306:3306
    hostname: banco_mysql
